# Welcome to Numpy

In [3]:
import numpy as np

***Creating array in Numpy***

In [4]:
 myarr =  np.array([1,5,3,2])
myarr

array([1, 5, 3, 2])

In [5]:
myarr[0] 

1

In [9]:
myarr[0] = 2

In [10]:
myarr

array([2, 5, 3, 2])

In [11]:
myarr =  np.array([[12,34,23,13]])
myarr

array([[12, 34, 23, 13]])

In [14]:
myarr[0][1]

34

In [17]:
emp =  np.empty((3,4))
emp

array([[8.66739171e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [8.01097888e-307, 1.04082753e-047, 5.28329145e-091,
        2.70237044e-056],
       [1.55054528e+184, 1.17714445e-047, 3.99910963e+252,
        1.73713355e-047]])

In [19]:
arr =  np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr.reshape(11,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

        Array

In [29]:
x =  [[1,2,3],[1,2,3],[1,2,3]]

In [31]:
arr =  np.array(x)

In [35]:
arr.sum(axis=1)

arr.sum()

18

In [36]:
arr.sum(axis=0)

array([3, 6, 9])

In [38]:
arr.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])