# Welcome to Numpy

In [2]:
import numpy as np

In [3]:
x =  np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
x

array([1, 2, 3, 4])

In [9]:
type(x)

numpy.ndarray

In [10]:
x[1] = 99

In [11]:
x

array([ 1, 99,  3,  4])

In [12]:
for i in x:
    print("i",i)

i 1
i 99
i 3
i 4


In [17]:
for i in range(90,120):
    x = np.append(x,i)

In [18]:
x

array([  1,  99,   3,   4,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119])

In [19]:
#Creating an list and pushing in numpy array

In [28]:
l = []
for i in range(0,5):
    myInput=  int(input("{s}Enter your Number {s} ".format(s=i+1)))
    l.append(myInput)
print(np.array(l))

1Enter your Number 1 90
2Enter your Number 2 32
3Enter your Number 3 45
4Enter your Number 4 322
5Enter your Number 5 456
[ 90  32  45 322 456]


Arr2 

In [34]:
Arr2 = np.array([[1,2,3],[33,44,55]])

In [31]:
Arr2

array([[ 1,  2,  3],
       [33, 44, 55]])

In [32]:
Arr2.ndim

2

In [35]:
# Starting of Special Numpy Array 

In [36]:
# 1. Araay filled with 0's

In [43]:
ar_Zero =  np.zeros(4)
ar_Zero1 =  np.zeros((2,4))
print(ar_Zero)
ar_Zero1

[0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
# 1. Araay filled with 1's

In [45]:
ar_one =  np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [46]:
# 3.Craete and empty array 

In [47]:
ar_empty =  np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


In [48]:
# 4.Create and empty with range 

In [50]:
arr_rn = np.arange(9)
print(arr_rn)

[0 1 2 3 4 5 6 7 8]


In [51]:
# 5. Array with diagonal filled with 1's 

In [52]:
ar_dig =  np.eye(3)
print(ar_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
ar_dig =  np.eye(3,9)
print(ar_dig)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]]


Creating Numpy with random numbers

In [73]:
np.random.randint(90,99)

94